export const USER_FETCH_REQUEST_ACTION = "USER_FETCH_REQUEST_ACTION";
export const USER_FETCH_RESULT_SUCCESS = "USER_FETCH_RESULT_SUCCESS";
export const USER_FETCH_RESULT_ERROR = "USER_FETCH_RESULT_ERROR";
